[2024-10-05T14:58:49.968+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: pdf_extraction_with_klippa.upload_to_s3 manual__2024-10-05T14:53:29.498039+00:00 [queued]>
[2024-10-05T14:58:49.981+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: pdf_extraction_with_klippa.upload_to_s3 manual__2024-10-05T14:53:29.498039+00:00 [queued]>
[2024-10-05T14:58:49.981+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-10-05T14:58:49.982+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2024-10-05T14:58:49.982+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-10-05T14:58:49.997+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): upload_to_s3> on 2024-10-05 14:53:29.498039+00:00
[2024-10-05T14:58:50.003+0000] {standard_task_runner.py:55} INFO - Started process 14723 to run task
[2024-10-05T14:58:50.005+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'pdf_extraction_with_klippa', 'upload_to_s3', 'manual__2024-10-05T14:53:29.498039+00:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/PDF-Klippa.py', '--cfg-path', '/tmp/tmp1ywqu9ib']
[2024-10-05T14:58:50.007+0000] {standard_task_runner.py:83} INFO - Job 126: Subtask upload_to_s3
[2024-10-05T14:58:50.032+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-05T14:58:50.110+0000] {task_command.py:389} INFO - Running <TaskInstance: pdf_extraction_with_klippa.upload_to_s3 manual__2024-10-05T14:53:29.498039+00:00 [running]> on host 93d8e18bedbe
[2024-10-05T14:58:50.226+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pdf_extraction_with_klippa
AIRFLOW_CTX_TASK_ID=upload_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2024-10-05T14:53:29.498039+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-05T14:53:29.498039+00:00
[2024-10-05T14:58:50.406+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/PDF-Klippa.py", line 115, in upload_to_s3
    klippa_s3_key = f'klippa/{os.path.basename(klippa_output_path)}'
  File "/usr/local/lib/python3.7/posixpath.py", line 146, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2024-10-05T14:58:50.424+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=pdf_extraction_with_klippa, task_id=upload_to_s3, execution_date=20241005T145329, start_date=20241005T145849, end_date=20241005T145850
[2024-10-05T14:58:50.440+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 126 for task upload_to_s3 (expected str, bytes or os.PathLike object, not NoneType; 14723)
[2024-10-05T14:58:50.459+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-10-05T14:58:50.484+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
