[2024-10-06T06:32:46.591+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: pdf_extraction_with_pymupdf_and_convertapi.extract_with_convertapi manual__2024-10-06T06:27:38.496417+00:00 [queued]>
[2024-10-06T06:32:46.601+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: pdf_extraction_with_pymupdf_and_convertapi.extract_with_convertapi manual__2024-10-06T06:27:38.496417+00:00 [queued]>
[2024-10-06T06:32:46.602+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-10-06T06:32:46.603+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2024-10-06T06:32:46.603+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-10-06T06:32:46.617+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_with_convertapi> on 2024-10-06 06:27:38.496417+00:00
[2024-10-06T06:32:46.621+0000] {standard_task_runner.py:55} INFO - Started process 7357 to run task
[2024-10-06T06:32:46.623+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'pdf_extraction_with_pymupdf_and_convertapi', 'extract_with_convertapi', 'manual__2024-10-06T06:27:38.496417+00:00', '--job-id', '282', '--raw', '--subdir', 'DAGS_FOLDER/ETL-ConvertAPI.py', '--cfg-path', '/tmp/tmpthkiymt7']
[2024-10-06T06:32:46.625+0000] {standard_task_runner.py:83} INFO - Job 282: Subtask extract_with_convertapi
[2024-10-06T06:32:46.645+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-06T06:32:46.724+0000] {task_command.py:389} INFO - Running <TaskInstance: pdf_extraction_with_pymupdf_and_convertapi.extract_with_convertapi manual__2024-10-06T06:27:38.496417+00:00 [running]> on host c14bde59b801
[2024-10-06T06:32:46.830+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pdf_extraction_with_pymupdf_and_convertapi
AIRFLOW_CTX_TASK_ID=extract_with_convertapi
AIRFLOW_CTX_EXECUTION_DATE=2024-10-06T06:27:38.496417+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-06T06:27:38.496417+00:00
[2024-10-06T06:32:46.975+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL-ConvertAPI.py", line 84, in extract_with_convertapi
    for pdf_path in download_paths:
TypeError: 'NoneType' object is not iterable
[2024-10-06T06:32:46.997+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=pdf_extraction_with_pymupdf_and_convertapi, task_id=extract_with_convertapi, execution_date=20241006T062738, start_date=20241006T063246, end_date=20241006T063246
[2024-10-06T06:32:47.014+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 282 for task extract_with_convertapi ('NoneType' object is not iterable; 7357)
[2024-10-06T06:32:47.037+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-10-06T06:32:47.071+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
