[2024-10-04T15:50:57.080+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: pdf_extraction_stages.list_pdfs_in_s3 manual__2024-10-04T15:50:56.317608+00:00 [queued]>
[2024-10-04T15:50:57.091+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: pdf_extraction_stages.list_pdfs_in_s3 manual__2024-10-04T15:50:56.317608+00:00 [queued]>
[2024-10-04T15:50:57.091+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-10-04T15:50:57.092+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2024-10-04T15:50:57.092+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-10-04T15:50:57.106+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): list_pdfs_in_s3> on 2024-10-04 15:50:56.317608+00:00
[2024-10-04T15:50:57.109+0000] {standard_task_runner.py:55} INFO - Started process 186 to run task
[2024-10-04T15:50:57.112+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'pdf_extraction_stages', 'list_pdfs_in_s3', 'manual__2024-10-04T15:50:56.317608+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/PDF-ETL.py', '--cfg-path', '/tmp/tmp8s8eqmn6']
[2024-10-04T15:50:57.113+0000] {standard_task_runner.py:83} INFO - Job 9: Subtask list_pdfs_in_s3
[2024-10-04T15:50:57.135+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-04T15:50:57.210+0000] {task_command.py:389} INFO - Running <TaskInstance: pdf_extraction_stages.list_pdfs_in_s3 manual__2024-10-04T15:50:56.317608+00:00 [running]> on host c4c00c210b92
[2024-10-04T15:50:57.314+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pdf_extraction_stages
AIRFLOW_CTX_TASK_ID=list_pdfs_in_s3
AIRFLOW_CTX_EXECUTION_DATE=2024-10-04T15:50:56.317608+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-04T15:50:56.317608+00:00
[2024-10-04T15:50:57.636+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/PDF-ETL.py", line 27, in list_pdfs_in_s3
    response = s3.list_objects_v2(Bucket=bucket_name)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the ListObjectsV2 operation: The AWS Access Key Id you provided does not exist in our records.
[2024-10-04T15:50:57.654+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=pdf_extraction_stages, task_id=list_pdfs_in_s3, execution_date=20241004T155056, start_date=20241004T155057, end_date=20241004T155057
[2024-10-04T15:50:57.671+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 9 for task list_pdfs_in_s3 (An error occurred (InvalidAccessKeyId) when calling the ListObjectsV2 operation: The AWS Access Key Id you provided does not exist in our records.; 186)
[2024-10-04T15:50:57.686+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-10-04T15:50:57.716+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
